vim.cmd([[packadd packer.nvim]])

return require("packer").startup(function(use)
    -- Packer can manage itself
    use("wbthomason/packer.nvim")
    use("scrooloose/nerdcommenter")
    use("tpope/vim-fugitive")
    use("christoomey/vim-tmux-navigator")
    use("rafi/awesome-vim-colorschemes")
    use("ryanoasis/vim-devicons")
    use("mhartington/formatter.nvim")
    use("lukas-reineke/indent-blankline.nvim")
    use("nvim-lua/plenary.nvim")
    use("nvim-telescope/telescope.nvim")
    use("JohnnyMorganz/StyLua")
    use("nvim-tree/nvim-tree.lua")
    use("nvim-lualine/lualine.nvim")
    use("nikvdp/neomux")
    use("kdheepak/tabline.nvim")
    use("lewis6991/gitsigns.nvim")
    use("phaazon/hop.nvim")
    use("karb94/neoscroll.nvim")
    use("folke/trouble.nvim")
    use("nvim-tree/nvim-web-devicons")
    use("nvim-treesitter/nvim-treesitter")
    use("neovim/nvim-lspconfig")
    use("hrsh7th/cmp-nvim-lsp")
    use("hrsh7th/cmp-buffer")
    use("hrsh7th/cmp-path")
    use("hrsh7th/cmp-cmdline")
    use("hrsh7th/nvim-cmp")
    use({ "L3MON4D3/LuaSnip", tag = "v2.*" })
    use("saadparwaiz1/cmp_luasnip")
    use({
        "nvim-telekasten/telekasten.nvim",
        requires = { "nvim-telescope/telescope.nvim" },
    })
    use("nvim-telekasten/calendar-vim")
    use("smjonas/inc-rename.nvim")
    use("alexander-born/bazel.nvim")
    use("alexander-born/cmp-bazel")
    use("github/copilot.vim")
    use("olimorris/codecompanion.nvim")
    use("atiladefreitas/dooing")
end)
