[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[git_branch]
symbol = " "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[time]
disabled = false
time_format = "%H:%m"

[sudo]
disabled = false
